
; Generated by CharPad C64 - Subchrist Software, 2003 - 2023.
; Assemble with 64TASS or similar.


; Display mode : Bitmap (Multi-colour).
; Matrix colouring method : Per Character.


; Colour values...

COLR_VIC_BG0 = 9
COLR_CMLO_BASE = 3
COLR_SMLO_BASE = 8
COLR_SMHI_BASE = 7


; Quantities and dimensions...

CHAR_COUNT = 1000
MAP_WID = 40
MAP_HEI = 25


; Data block sizes (in bytes)...

SZ_CHARSET_DATA = 8000 ; ($1f40)
SZ_CHARSET_ATTRIB_DATA = 1000 ; ($3e8)
SZ_MAP_DATA = 1000 ; ($3e8)


; Data block addresses (dummy values)...

addr_charset_data = $1000
addr_charset_attrib_L1_data = $1000
addr_charset_attrib_L2_data = $1000
addr_map_data = $1000




; * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




; CharSet Data...
; 1000 images, 8 bytes per image, total size is 8000 ($1f40) bytes.

* = addr_charset_data
charset_data

.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fc,$cf,$ff,$ff,$ff,$ff,$ff
.byte $ff,$fc,$3f,$f3,$c3,$ff,$c3,$ff,$c3,$ff,$ff,$f3,$ff,$ff,$ff,$ff
.byte $cf,$ff,$ff,$f3,$fc,$ff,$f0,$ff,$ff,$ff,$cf,$ff,$ff,$c3,$ff,$ff
.byte $ff,$ff,$3f,$cf,$ff,$ff,$ff,$cb,$3f,$3f,$ff,$fc,$fc,$fc,$f2,$91
.byte $f3,$fc,$ff,$ff,$ff,$3e,$68,$08,$cf,$3f,$cf,$ff,$c6,$42,$80,$00
.byte $ef,$da,$df,$df,$cf,$ce,$c0,$3c,$a5,$a9,$67,$9f,$3f,$3f,$bf,$bf
.byte $80,$a6,$53,$af,$6b,$63,$a3,$80,$ff,$ff,$fe,$ff,$ff,$fe,$ff,$fb
.byte $ab,$a8,$ac,$af,$90,$bc,$7f,$30,$7c,$ff,$0c,$c8,$f3,$8c,$00,$f3
.byte $c3,$03,$38,$0c,$38,$2b,$ec,$2c,$33,$00,$f0,$00,$00,$c3,$cf,$f0
.byte $0f,$b3,$23,$00,$00,$00,$00,$c3,$5f,$80,$c0,$0c,$00,$0c,$03,$0f
.byte $0d,$fe,$fd,$fd,$fe,$3f,$3f,$d5,$80,$7c,$d7,$f5,$ff,$df,$ae,$ef
.byte $04,$53,$7f,$bf,$bf,$7f,$ff,$ff,$7c,$fe,$fe,$fe,$fc,$fc,$fc,$fe
.byte $3f,$3f,$0f,$0f,$f3,$ff,$ff,$ff,$cc,$fc,$cf,$ff,$3f,$fc,$ff,$ff
.byte $f3,$30,$3f,$fc,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$cf,$f3
.byte $f3,$ff,$fc,$fc,$fc,$ff,$ff,$ff,$ff,$ff,$3f,$f3,$fc,$3c,$3c,$fc
.byte $ff,$ff,$ff,$fc,$ff,$ff,$ff,$ff,$3f,$3f,$ff,$ff,$ff,$ff,$ff,$ff
.byte $f0,$f0,$30,$ff,$ff,$ff,$ff,$ff,$ff,$cf,$cf,$33,$fc,$cf,$ff,$30
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$fc,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$fe,$fa,$ea,$aa,$ea,$aa,$aa,$aa,$fa,$fe,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$8f,$9b,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$fc,$ff,$ff,$ff,$ff,$ff,$fe,$ff,$cf,$c0,$f0,$fc,$f9,$f0,$f8
.byte $ff,$ff,$ff,$3b,$e7,$03,$02,$0d,$f3,$f1,$18,$88,$80,$08,$00,$00
.byte $14,$40,$00,$c0,$00,$c0,$00,$0c,$c0,$00,$c0,$00,$00,$c0,$90,$80
.byte $03,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0c,$3b,$00,$00,$00,$03
.byte $03,$00,$00,$00,$c0,$00,$00,$0c,$da,$c9,$37,$07,$0c,$c0,$00,$cc
.byte $55,$08,$bf,$fe,$fa,$0a,$48,$b8,$a8,$af,$ff,$ff,$cf,$c3,$fc,$55
.byte $c0,$ff,$00,$c0,$ff,$3c,$fa,$5a,$3c,$c0,$3d,$01,$37,$f7,$ae,$aa
.byte $40,$73,$cc,$f0,$c3,$3d,$aa,$aa,$3f,$3c,$c3,$0c,$30,$cf,$56,$aa
.byte $0f,$3c,$f3,$fc,$c3,$a5,$aa,$a0,$20,$80,$a8,$02,$5f,$ff,$ff,$4c
.byte $5f,$57,$07,$40,$aa,$ab,$0f,$1f,$af,$af,$af,$af,$ae,$ac,$ac,$a4
.byte $84,$83,$40,$43,$0f,$3f,$3f,$ff,$ab,$1b,$fd,$ff,$ff,$ff,$ff,$ff
.byte $00,$03,$33,$ea,$ff,$ef,$bf,$ff,$ff,$ff,$ff,$ff,$af,$fe,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ef,$fe,$ff,$ff,$ff,$f3,$f0,$ff,$fc,$bf
.byte $ff,$ff,$ff,$ff,$ff,$0f,$cf,$0e,$c3,$ff,$fc,$ff,$ff,$ff,$bf,$bc
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$cc,$fc,$ff,$ff,$f3
.byte $cf,$ff,$0c,$ff,$30,$cf,$0f,$ff,$cf,$fc,$ff,$3c,$ff,$ff,$ff,$ff
.byte $ff,$fb,$3f,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fc,$fc,$ff,$ff,$ff,$ff
.byte $3e,$cf,$f3,$ff,$cf,$c0,$fc,$ff,$ff,$ff,$ff,$ff,$ff,$f0,$ff,$ff
.byte $bf,$bb,$ba,$ba,$aa,$bc,$b0,$bf,$ff,$fa,$fa,$da,$fa,$fa,$7a,$da
.byte $55,$95,$95,$97,$8e,$bf,$bf,$bf,$aa,$2f,$0f,$1f,$6f,$5f,$4f,$4f
.byte $f3,$7f,$6a,$43,$4b,$6b,$62,$4b,$bc,$bc,$dc,$9c,$8c,$bc,$bc,$bf
.byte $c8,$c8,$c8,$fb,$08,$cc,$ec,$e4,$cc,$cc,$0c,$cc,$ff,$cc,$c3,$cc
.byte $cc,$c0,$cc,$cc,$f3,$f3,$ff,$fe,$20,$0f,$af,$8f,$4f,$6f,$6f,$af
.byte $20,$c0,$e8,$e2,$e2,$c8,$c7,$fd,$02,$0a,$00,$08,$2f,$75,$d1,$10
.byte $00,$00,$01,$d5,$af,$a3,$e3,$23,$0f,$fe,$fd,$fd,$fd,$fc,$7e,$3e
.byte $e4,$a7,$af,$af,$af,$af,$af,$af,$51,$f0,$f0,$f0,$f0,$f6,$f6,$f6
.byte $a5,$af,$2f,$2f,$7f,$7f,$7f,$7f,$fc,$fc,$fc,$fe,$fb,$bb,$a3,$ff
.byte $ed,$f5,$f5,$f5,$fd,$f5,$ea,$4f,$97,$97,$97,$b3,$bf,$ff,$ab,$84
.byte $f4,$f5,$f1,$ba,$aa,$bf,$81,$21,$a4,$a4,$f7,$ff,$fb,$7a,$a8,$ac
.byte $25,$3e,$be,$7e,$7e,$be,$3e,$be,$a3,$6f,$4f,$bf,$6a,$96,$96,$92
.byte $ff,$ff,$fe,$fb,$3f,$ff,$7f,$57,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$fe,$fb,$ff,$ff,$ff,$fe,$ff,$bf,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fa,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $c4,$a0,$84,$ea,$cf,$cf,$cf,$cf,$3c,$0f,$03,$8b,$ea,$fe,$ff,$ff
.byte $3f,$ff,$ff,$ff,$ff,$bf,$fa,$ff,$cf,$cf,$ff,$ff,$ff,$ff,$bf,$99
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$7f,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$3f,$0f,$3f,$3f,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fc,$ff,$ff,$ff,$ff,$03,$c0,$fc
.byte $ea,$ea,$e9,$ea,$ef,$ff,$ff,$ff,$5f,$1f,$9f,$af,$af,$9f,$8f,$5f
.byte $eb,$ea,$da,$ff,$ff,$ff,$ff,$ff,$9f,$9f,$9f,$ff,$ff,$ff,$ff,$ff
.byte $e2,$ea,$db,$d3,$e3,$eb,$ea,$c2,$bf,$ff,$ff,$ff,$d1,$cb,$be,$eb
.byte $c8,$fa,$fa,$f8,$f7,$fd,$fe,$fc,$8b,$8f,$bf,$7f,$ff,$fc,$fc,$fc
.byte $fc,$ff,$ff,$ff,$2f,$2f,$2e,$26,$2f,$ff,$6f,$0f,$cf,$cf,$af,$5f
.byte $c7,$c7,$c7,$cf,$cf,$ff,$ff,$fe,$a9,$a0,$a7,$bf,$b7,$ff,$d3,$c3
.byte $13,$bf,$db,$df,$d2,$d2,$d2,$d0,$be,$7e,$bf,$bf,$7f,$7f,$7f,$6f
.byte $af,$af,$bf,$bf,$bf,$be,$bd,$bd,$fc,$fc,$fc,$fc,$be,$be,$be,$7d
.byte $bc,$7c,$7c,$7c,$be,$fe,$fe,$fd,$97,$9f,$9f,$3f,$7f,$7f,$7f,$3d
.byte $fc,$fc,$ff,$ff,$af,$af,$5b,$03,$60,$62,$2b,$4b,$eb,$d7,$e7,$ef
.byte $3f,$ff,$ff,$ff,$f5,$d6,$c8,$d8,$a9,$e2,$f2,$fa,$f2,$f1,$fd,$fd
.byte $7e,$7e,$7e,$7e,$be,$3e,$7f,$7f,$4f,$7f,$bf,$fe,$fe,$fe,$f2,$f2
.byte $7d,$fa,$3a,$fa,$de,$df,$ff,$d7,$ea,$fe,$03,$4b,$5b,$c8,$fe,$ff
.byte $ef,$ff,$ff,$5b,$45,$4b,$4b,$4b,$ff,$ff,$ff,$ff,$7f,$a7,$8a,$93
.byte $ff,$ff,$bf,$bf,$bf,$bf,$af,$65,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$bf
.byte $cf,$cf,$ff,$ff,$ff,$f3,$f3,$f3,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$b7,$bf,$bf,$80,$b0,$b0,$80,$a0
.byte $fb,$bf,$0f,$cf,$00,$0c,$00,$00,$ff,$5f,$5f,$af,$2f,$13,$03,$3b
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$3f,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$f9,$fc,$f4,$e0,$c0,$80,$2c,$0f,$0f,$0f,$0f,$0f,$0f,$0f,$0f
.byte $c0,$c0,$c0,$d0,$e5,$e0,$c0,$c8,$0f,$0f,$0f,$0f,$0f,$2f,$0f,$0f
.byte $c5,$c3,$d3,$cb,$cb,$df,$ef,$cf,$bf,$ff,$ff,$f0,$c1,$e5,$e9,$e6
.byte $fc,$fc,$fc,$fd,$fe,$fe,$fe,$fc,$fc,$fe,$fe,$fe,$fe,$fc,$fd,$7f
.byte $3d,$75,$7d,$ff,$4b,$0a,$0a,$0a,$af,$af,$8f,$0f,$0f,$cf,$df,$ef
.byte $ff,$ff,$ff,$ff,$df,$ef,$eb,$eb,$43,$03,$07,$bf,$b7,$bf,$91,$a1
.byte $fb,$ff,$ff,$ff,$fa,$f9,$f9,$f9,$5f,$5f,$af,$5f,$5f,$5f,$5f,$af
.byte $be,$fe,$fe,$fe,$fe,$fa,$fa,$fa,$bf,$bf,$bf,$8f,$6f,$6f,$6f,$9f
.byte $fc,$fc,$f4,$f6,$f6,$fa,$f6,$f4,$7f,$7f,$7f,$bf,$be,$3e,$be,$3f
.byte $ff,$ff,$ff,$ff,$55,$aa,$0f,$4f,$ef,$df,$ef,$ef,$af,$8b,$d7,$d7
.byte $ff,$ff,$ff,$ff,$d5,$ca,$ca,$fa,$fd,$fe,$fe,$fe,$a0,$82,$fe,$f9
.byte $bf,$bf,$bf,$bf,$7f,$7e,$7e,$7e,$f2,$f2,$fe,$fe,$fe,$3e,$7f,$7f
.byte $f6,$35,$05,$b5,$bd,$bf,$2f,$0f,$ff,$1f,$0b,$3a,$3a,$fa,$ff,$fd
.byte $bd,$bf,$bf,$8b,$8f,$8d,$8d,$b1,$bd,$bd,$ad,$bf,$af,$8b,$8f,$bf
.byte $03,$01,$4d,$fd,$ff,$ff,$bf,$4b,$fd,$7f,$3a,$fa,$7a,$fa,$ff,$ff
.byte $f3,$bf,$aa,$39,$b9,$f9,$f9,$a9,$ff,$ff,$af,$2a,$26,$95,$81,$80
.byte $ff,$ff,$ff,$7f,$67,$96,$aa,$6a,$f8,$f0,$f0,$f8,$f8,$a9,$59,$06
.byte $00,$00,$0d,$37,$a3,$80,$3d,$fe,$2f,$af,$6f,$6f,$6f,$af,$af,$ac
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$c3
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $f0,$38,$80,$cf,$f3,$00,$2e,$3f,$0f,$0f,$0f,$8f,$40,$40,$84,$a8
.byte $c0,$c2,$c2,$c0,$00,$00,$00,$00,$0f,$0f,$0f,$4f,$40,$12,$02,$28
.byte $a6,$9e,$8e,$9f,$ff,$fd,$fc,$ff,$ff,$ff,$ff,$fc,$80,$6a,$65,$66
.byte $fc,$fc,$fd,$3e,$ad,$ae,$ae,$ad,$2a,$2a,$fa,$fe,$ff,$fe,$3e,$3e
.byte $ff,$ff,$fd,$f5,$2a,$2a,$0a,$29,$da,$fa,$0a,$0a,$04,$07,$5d,$f7
.byte $82,$80,$80,$8f,$7f,$7f,$7f,$71,$f1,$f6,$fd,$fd,$aa,$b1,$b1,$31
.byte $fe,$fe,$ff,$f8,$e0,$e0,$e0,$ef,$5a,$f6,$f2,$52,$54,$5f,$fd,$ff
.byte $5b,$5b,$5f,$5f,$af,$af,$ab,$ab,$7a,$5a,$7a,$da,$df,$ff,$50,$50
.byte $ac,$ac,$a5,$85,$44,$c5,$4c,$0c,$bf,$9f,$5f,$57,$55,$55,$91,$95
.byte $ff,$ff,$ff,$fc,$55,$a0,$a0,$a0,$69,$3d,$1f,$f5,$70,$3b,$6b,$6b
.byte $ff,$ff,$ff,$bf,$06,$06,$06,$0a,$5f,$5f,$73,$c2,$c2,$c2,$ce,$ff
.byte $be,$be,$bd,$7e,$62,$60,$60,$a8,$fa,$fa,$6a,$fa,$4f,$c6,$37,$f6
.byte $fa,$f8,$a9,$7f,$7f,$3f,$3d,$fb,$ee,$06,$a5,$f5,$c5,$ff,$ff,$2f
.byte $ff,$ff,$56,$cb,$db,$5b,$fb,$ff,$7f,$7e,$a5,$7f,$5f,$4c,$7e,$7e
.byte $be,$8e,$69,$fe,$ff,$ff,$df,$c3,$ff,$b7,$5a,$b5,$f5,$fc,$ff,$ff
.byte $fe,$fe,$6a,$5a,$5a,$5a,$da,$fe,$fe,$fe,$5f,$ff,$ff,$ff,$eb,$e8
.byte $f6,$f6,$6a,$e4,$d5,$f5,$55,$95,$80,$81,$fd,$a3,$af,$bf,$bf,$b3
.byte $fb,$bf,$7f,$fe,$fe,$ef,$af,$af,$ac,$6f,$fe,$2f,$a3,$a3,$ac,$ac
.byte $fc,$3f,$7f,$cf,$3f,$ff,$ff,$ff,$ff,$ff,$57,$ff,$ff,$fc,$fc,$c0
.byte $ff,$ff,$f7,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$3f,$cf,$f3,$c3,$cf
.byte $60,$04,$5a,$1a,$c4,$f0,$fd,$ff,$40,$00,$f3,$04,$00,$0c,$33,$aa
.byte $00,$00,$00,$00,$03,$23,$07,$5f,$3e,$b7,$f7,$ff,$ff,$bf,$bf,$7f
.byte $ff,$ff,$ff,$df,$9d,$be,$be,$fd,$fd,$c8,$c4,$c0,$da,$ff,$ff,$af
.byte $6d,$ae,$ae,$9f,$ff,$ff,$f7,$f6,$3d,$3d,$bd,$fd,$fd,$ff,$3f,$3f
.byte $bb,$fb,$ff,$ff,$45,$45,$55,$4f,$ff,$f9,$c9,$c9,$c5,$db,$fe,$eb
.byte $d1,$d2,$41,$4b,$bf,$bf,$bf,$e1,$b2,$bf,$7d,$77,$7d,$f2,$fa,$b8
.byte $ef,$ef,$ae,$f8,$74,$54,$56,$6f,$ae,$a7,$ff,$5f,$5e,$2b,$aa,$ab
.byte $fe,$fe,$fe,$3e,$ba,$fe,$ae,$fd,$a4,$a4,$ef,$ef,$ff,$af,$a1,$e1
.byte $f4,$ff,$8b,$8f,$ba,$b4,$f4,$f8,$b1,$fd,$f5,$ff,$55,$91,$91,$91
.byte $2f,$7f,$ff,$55,$a0,$ac,$ac,$ac,$7f,$7f,$7f,$50,$2b,$2b,$2b,$3d
.byte $df,$ff,$d5,$0a,$02,$0a,$0a,$5f,$ff,$f3,$ac,$c1,$c1,$cd,$eb,$eb
.byte $f4,$f4,$b4,$bc,$bc,$be,$ff,$fd,$ff,$ff,$ff,$5e,$7a,$4a,$ca,$fa
.byte $26,$86,$aa,$ff,$ff,$ff,$ff,$ff,$3f,$f5,$f5,$f5,$ad,$af,$bf,$ab
.byte $ff,$ff,$4f,$5a,$78,$fa,$fa,$ff,$bd,$bd,$bf,$bf,$8b,$8d,$b2,$86
.byte $81,$81,$a9,$bf,$ff,$ff,$ff,$ff,$1f,$10,$1f,$93,$a3,$af,$ab,$ab
.byte $a9,$e9,$35,$25,$25,$35,$b5,$b9,$94,$94,$a8,$bb,$ab,$aa,$97,$94
.byte $ad,$ad,$ad,$6f,$7f,$7f,$7f,$bf,$50,$90,$82,$fa,$fe,$ff,$ff,$ff
.byte $ff,$ff,$fd,$fc,$ed,$af,$af,$bf,$9f,$af,$a3,$a0,$bf,$bf,$b3,$bf
.byte $ff,$ff,$ff,$fe,$ca,$3a,$ca,$fa,$a8,$aa,$8a,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$3f,$bf,$bf,$af,$af,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $55,$55,$55,$55,$55,$55,$55,$55,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$bf,$6f,$af,$6f,$af,$fb,$ff,$ff,$fb,$ef,$ef,$9f,$bf
.byte $ff,$fb,$fb,$ef,$bf,$bd,$bd,$be,$fe,$e4,$f0,$f0,$f6,$ff,$fe,$eb
.byte $66,$6a,$a9,$9b,$fb,$fb,$fc,$ec,$2f,$2f,$fe,$fa,$fe,$ef,$2f,$2f
.byte $fe,$ff,$ff,$f9,$45,$49,$56,$7e,$7f,$70,$70,$70,$6b,$7f,$ff,$ff
.byte $87,$47,$43,$5b,$af,$ab,$ad,$f5,$1e,$16,$5a,$9a,$af,$ff,$ff,$ff
.byte $aa,$a9,$57,$7f,$ff,$ff,$ff,$ff,$55,$d5,$a9,$ff,$fd,$fe,$fe,$ff
.byte $e9,$a9,$66,$6f,$7f,$5e,$90,$55,$b0,$69,$fa,$fa,$fe,$fd,$f4,$f5
.byte $00,$98,$10,$00,$4f,$ef,$30,$00,$2b,$ef,$cf,$cf,$03,$40,$40,$10
.byte $be,$fe,$fe,$1a,$04,$00,$00,$14,$ea,$ea,$ff,$3f,$14,$00,$02,$04
.byte $f5,$f7,$ff,$c6,$ca,$ca,$ca,$c9,$d7,$55,$59,$1b,$db,$d7,$2b,$fb
.byte $f8,$a8,$ba,$fb,$fb,$fb,$fb,$fb,$fa,$f9,$6d,$25,$01,$01,$c1,$f1
.byte $af,$a7,$ab,$ab,$2b,$6f,$0f,$0f,$f2,$f0,$f0,$f0,$f9,$e8,$d8,$d0
.byte $ff,$0f,$c6,$05,$f5,$b5,$be,$be,$6b,$ab,$af,$1f,$8f,$8f,$8f,$6f
.byte $f9,$f9,$f9,$fa,$ea,$ea,$c2,$e9,$fe,$fc,$ff,$ff,$bf,$bf,$bf,$7f
.byte $ed,$e4,$24,$24,$24,$ec,$ec,$ec,$6c,$40,$5b,$af,$6f,$46,$73,$7f
.byte $3e,$1e,$16,$7e,$7f,$7f,$7f,$36,$bf,$bf,$8f,$8f,$7f,$7f,$7f,$bf
.byte $7f,$7c,$7c,$68,$af,$af,$af,$ff,$8f,$8f,$9f,$bf,$bf,$bf,$bf,$bf
.byte $3b,$ff,$ff,$ff,$ff,$cf,$fc,$ff,$2b,$2b,$8b,$8b,$bf,$ff,$ff,$ff
.byte $a3,$af,$af,$af,$bf,$b3,$0f,$bf,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$f4,$00,$00,$00,$02,$aa,$6a,$53,$0f,$3f,$3f,$ff,$ff
.byte $5b,$ab,$6b,$ff,$ff,$ff,$ff,$ff,$bf,$ff,$ff,$fb,$ab,$aa,$a9,$a5
.byte $fa,$fb,$fb,$fb,$ff,$af,$5a,$55,$f8,$f8,$f0,$f8,$75,$bf,$bf,$1f
.byte $54,$14,$17,$6f,$ef,$af,$aa,$be,$2b,$3f,$ee,$fe,$fa,$a5,$56,$55
.byte $5a,$56,$66,$6f,$ff,$ff,$ef,$ff,$55,$5e,$6f,$fb,$bb,$9f,$fe,$7e
.byte $5a,$9a,$b8,$bf,$7f,$6e,$5f,$98,$ff,$ff,$3f,$2f,$9b,$a2,$6a,$90
.byte $ff,$ff,$ff,$ff,$ff,$ff,$36,$01,$ff,$ff,$ff,$fd,$fe,$40,$8a,$aa
.byte $03,$00,$5b,$fb,$3b,$3b,$39,$09,$5f,$5f,$7c,$78,$4a,$60,$a1,$62
.byte $1a,$dc,$30,$70,$d2,$c0,$c0,$12,$0c,$30,$0f,$4c,$0c,$8e,$a2,$12
.byte $c0,$81,$f0,$a0,$20,$00,$07,$4f,$80,$80,$b0,$0c,$c0,$08,$00,$00
.byte $70,$fa,$3b,$0f,$00,$00,$0c,$05,$37,$f4,$fc,$f1,$b9,$2b,$3a,$51
.byte $aa,$54,$54,$00,$fc,$fd,$fd,$31,$a8,$a8,$4a,$06,$57,$4b,$4f,$6f
.byte $3f,$7f,$ff,$fc,$fd,$f1,$f1,$ff,$ce,$06,$06,$f6,$fe,$fe,$fe,$fe
.byte $ae,$aa,$cd,$82,$c1,$81,$bd,$8c,$6f,$6f,$6f,$6f,$4f,$43,$43,$43
.byte $bc,$bc,$bf,$af,$af,$a7,$a4,$af,$bf,$bf,$bf,$ff,$ff,$fd,$fd,$fd
.byte $b8,$72,$72,$72,$72,$b3,$b3,$b3,$97,$ac,$ae,$ef,$2a,$96,$95,$83
.byte $10,$10,$9b,$97,$9f,$bf,$3f,$ff,$ff,$fe,$fe,$fa,$fa,$e5,$d2,$ff
.byte $fe,$fa,$ea,$a9,$a7,$af,$af,$7f,$7f,$7f,$7f,$7f,$7f,$6a,$6a,$6a
.byte $ff,$ff,$ff,$ff,$ff,$ef,$6b,$6a,$aa,$fe,$fe,$fe,$fe,$fe,$fe,$aa
.byte $f8,$fa,$fa,$fa,$fa,$fa,$fa,$fa,$ff,$fc,$ff,$fc,$fc,$ff,$ff,$ff
.byte $03,$3f,$0c,$56,$7e,$7a,$da,$7a,$ae,$be,$ab,$ad,$f8,$8c,$ff,$3e
.byte $ee,$ee,$fe,$3e,$2b,$0a,$0b,$53,$bb,$ef,$eb,$ef,$eb,$ad,$ca,$bf
.byte $cf,$f3,$b8,$ff,$fe,$3e,$be,$ea,$a7,$2f,$ed,$6a,$ab,$ab,$3f,$3f
.byte $ab,$bd,$ff,$eb,$af,$af,$a1,$c5,$ff,$ee,$f8,$38,$fc,$20,$ef,$d4
.byte $bb,$be,$20,$12,$36,$00,$00,$74,$f7,$37,$0f,$80,$80,$90,$03,$82
.byte $a5,$e8,$ec,$d8,$cc,$0f,$32,$00,$bd,$3d,$0d,$cd,$02,$ae,$91,$29
.byte $12,$d2,$cc,$c3,$13,$04,$44,$11,$fc,$c3,$3a,$b8,$2a,$d6,$10,$5e
.byte $e7,$27,$07,$2f,$ff,$ff,$fd,$ad,$d8,$da,$f4,$ff,$ff,$f7,$d4,$ff
.byte $f0,$07,$4e,$af,$bb,$ae,$ff,$c5,$80,$8a,$51,$73,$e0,$c0,$d0,$bc
.byte $8c,$00,$80,$30,$00,$30,$f1,$02,$0a,$01,$0f,$3c,$f0,$00,$30,$3c
.byte $a5,$a5,$81,$00,$00,$03,$0b,$c0,$77,$aa,$87,$0c,$c0,$00,$0e,$35
.byte $b1,$90,$64,$4a,$09,$f5,$32,$c1,$4f,$4f,$4f,$4f,$24,$a0,$aa,$80
.byte $ff,$ff,$ff,$ff,$a4,$08,$00,$a0,$53,$5b,$5b,$5b,$8b,$88,$b8,$8f
.byte $b8,$88,$81,$8d,$91,$91,$18,$10,$fd,$ff,$ff,$f3,$c3,$fb,$fb,$fb
.byte $ff,$ff,$ff,$7f,$42,$6a,$42,$88,$ab,$ab,$a1,$b1,$31,$3f,$3f,$ff
.byte $92,$92,$72,$53,$b3,$83,$83,$83,$42,$5e,$ff,$ff,$5f,$53,$54,$42
.byte $ff,$ff,$ff,$ff,$9a,$9a,$12,$92,$ff,$ff,$ff,$ff,$a9,$a5,$45,$85
.byte $7e,$70,$70,$71,$27,$2b,$2b,$a2,$d5,$f5,$ff,$3a,$3b,$3e,$29,$2b
.byte $6a,$6a,$2a,$fa,$d5,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$aa,$55,$a5,$aa
.byte $5a,$6a,$72,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$bf,$af,$ab,$8a,$96
.byte $1a,$45,$fa,$f2,$3e,$cf,$f0,$2c,$f3,$cb,$b3,$f8,$b3,$fc,$be,$f0
.byte $cb,$28,$c2,$f1,$04,$f2,$3c,$ff,$ff,$ff,$de,$de,$3f,$1e,$4b,$4f
.byte $bd,$ad,$be,$f6,$f6,$a6,$d6,$e6,$7f,$7b,$7b,$7f,$ff,$ff,$ff,$ff
.byte $07,$4f,$0f,$cf,$30,$33,$33,$06,$8b,$0f,$bc,$3c,$8f,$8a,$86,$aa
.byte $ce,$f3,$c0,$0f,$f0,$00,$8c,$00,$0c,$03,$03,$00,$b3,$31,$3f,$0c
.byte $c0,$f1,$f0,$0c,$c5,$e7,$2c,$20,$be,$ce,$c2,$f2,$1a,$c2,$02,$60
.byte $7a,$60,$30,$01,$12,$0e,$00,$03,$a0,$e3,$23,$74,$e0,$1e,$30,$01
.byte $83,$23,$00,$3c,$de,$5b,$2c,$cc,$7a,$b0,$fc,$c0,$f0,$00,$80,$8c
.byte $00,$00,$0c,$00,$00,$00,$00,$00,$d5,$05,$35,$f2,$0e,$0a,$0d,$fa
.byte $00,$b4,$b4,$be,$ae,$cc,$3f,$6f,$03,$0f,$11,$55,$74,$f8,$fa,$0a
.byte $fc,$04,$00,$04,$00,$00,$28,$d2,$0f,$0f,$00,$00,$00,$00,$00,$40
.byte $00,$08,$00,$18,$70,$fd,$33,$33,$10,$51,$02,$84,$dd,$ff,$fb,$20
.byte $2f,$3e,$3b,$7b,$ea,$ee,$df,$3f,$3f,$73,$fc,$ff,$67,$6b,$a9,$fd
.byte $14,$04,$20,$20,$42,$5e,$5e,$df,$f7,$e7,$cb,$c3,$c3,$a3,$a2,$86
.byte $cf,$cc,$ce,$cf,$fe,$cf,$3f,$cf,$83,$8c,$8c,$4c,$4c,$fc,$ff,$3f
.byte $43,$43,$43,$83,$83,$83,$83,$c3,$42,$72,$7f,$ff,$ff,$0f,$0b,$8a
.byte $59,$59,$51,$5f,$5f,$5f,$eb,$ab,$c9,$f7,$df,$ff,$f6,$fa,$ea,$6a
.byte $ef,$6f,$ef,$ef,$ec,$c1,$d7,$17,$3f,$27,$7f,$bf,$bf,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fe
.byte $af,$bf,$bf,$bf,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fd,$fe,$fe,$f6
.byte $c2,$3c,$83,$e2,$f1,$bc,$0b,$c8,$4f,$b0,$9f,$10,$6f,$18,$83,$28
.byte $0c,$fe,$0c,$f3,$3c,$ff,$30,$c3,$42,$16,$92,$0f,$8f,$28,$ba,$3b
.byte $5f,$ff,$ff,$bf,$ff,$fa,$da,$da,$aa,$a9,$af,$8f,$7f,$7f,$7f,$b3
.byte $cf,$cf,$8f,$0f,$0f,$43,$00,$09,$f7,$ff,$ff,$ff,$ef,$ff,$ff,$bf
.byte $5c,$2c,$75,$71,$22,$9f,$6a,$69,$01,$06,$86,$c4,$dc,$cc,$ec,$ec
.byte $04,$04,$80,$8c,$cc,$3b,$33,$03,$48,$08,$23,$00,$c3,$30,$c0,$00
.byte $3c,$81,$01,$fa,$3c,$cf,$08,$00,$0e,$1a,$dd,$c3,$30,$00,$c0,$c0
.byte $df,$f0,$ef,$a3,$6d,$03,$0b,$2f,$dc,$08,$c8,$fa,$fa,$fb,$c0,$02
.byte $00,$0f,$ff,$bf,$f5,$5b,$7a,$54,$f6,$f6,$fa,$a3,$7d,$da,$2a,$80
.byte $0d,$7d,$02,$e0,$ab,$1a,$1f,$3c,$fb,$39,$03,$30,$80,$83,$5c,$0c
.byte $09,$3f,$15,$12,$0c,$0e,$3e,$e6,$cd,$ca,$80,$00,$0d,$00,$cc,$e3
.byte $2f,$00,$1c,$00,$00,$00,$af,$20,$aa,$ab,$af,$0f,$03,$07,$10,$00
.byte $5c,$c0,$3c,$f0,$ff,$ab,$ab,$aa,$13,$20,$33,$b3,$ff,$ff,$cc,$aa
.byte $3f,$ff,$3f,$07,$df,$ab,$ab,$a8,$8d,$03,$4b,$3f,$ff,$fb,$3b,$ff
.byte $bf,$b0,$73,$48,$6e,$e2,$d0,$f8,$aa,$aa,$aa,$fe,$ff,$ff,$3f,$ff
.byte $49,$69,$c9,$f1,$bc,$af,$af,$ac,$cf,$cf,$ff,$ff,$3f,$83,$a8,$2a
.byte $ae,$a1,$a3,$83,$8f,$83,$82,$cf,$54,$90,$90,$80,$b2,$fe,$fc,$ef
.byte $27,$2f,$1f,$1f,$ff,$7f,$a2,$a2,$ff,$ff,$ff,$ff,$ff,$af,$aa,$aa
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ab,$aa,$ab,$ab,$af,$af,$bf,$bf,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$fd,$af,$af,$9f,$bf,$8d,$7d,$fd,$fe
.byte $3c,$43,$03,$c5,$7c,$a4,$aa,$aa,$43,$c4,$c0,$3c,$03,$10,$aa,$aa
.byte $28,$42,$28,$23,$03,$07,$ff,$77,$ae,$6e,$ef,$ae,$ad,$ad,$ec,$bd
.byte $ed,$8f,$bf,$bf,$bb,$fb,$f9,$eb,$b3,$b3,$73,$73,$73,$43,$47,$83
.byte $8f,$8b,$80,$89,$a7,$af,$9f,$3d,$ff,$ff,$f7,$d5,$78,$ca,$62,$82
.byte $d7,$f2,$f2,$3c,$b7,$8d,$88,$80,$20,$20,$20,$70,$f3,$e4,$ef,$ce
.byte $00,$03,$00,$00,$c0,$c0,$06,$98,$00,$00,$00,$00,$00,$00,$9d,$a8
.byte $00,$20,$00,$00,$fb,$fd,$ea,$eb,$01,$04,$74,$f0,$a6,$ad,$f8,$e1
.byte $00,$4e,$cc,$a1,$ab,$80,$06,$02,$33,$c0,$04,$00,$70,$00,$00,$aa
.byte $52,$48,$07,$0f,$3f,$ff,$fc,$ff,$0f,$ff,$fc,$ff,$ff,$ef,$ec,$2e
.byte $ff,$fc,$ff,$3f,$ff,$f1,$ff,$ff,$8f,$0f,$c0,$cc,$c2,$3f,$ff,$dd
.byte $3f,$3f,$3f,$a0,$00,$00,$40,$d0,$ae,$ef,$65,$66,$a2,$25,$e5,$e5
.byte $fa,$02,$a2,$50,$c0,$c0,$ff,$ff,$a8,$55,$72,$3e,$3c,$ff,$ff,$ff
.byte $f5,$31,$a2,$03,$0f,$ff,$5f,$57,$a5,$ff,$c3,$ff,$ff,$fd,$f6,$fa
.byte $45,$3f,$2a,$30,$fc,$ff,$7f,$5a,$17,$f5,$e3,$e0,$ad,$ff,$fc,$97
.byte $fa,$f0,$f6,$5d,$53,$7f,$b1,$80,$fe,$f6,$8a,$aa,$59,$f5,$f7,$ff
.byte $ac,$a4,$96,$56,$5e,$7e,$fe,$fd,$3f,$3f,$ff,$fb,$fb,$ff,$ff,$7f
.byte $af,$ef,$7f,$7f,$ff,$ff,$ff,$ff,$fb,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $cf,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fb,$f7,$fb,$e5
.byte $fc,$fe,$fd,$ff,$ff,$ff,$ff,$ff,$6a,$da,$d9,$df,$cf,$73,$bd,$b7
.byte $a9,$ab,$67,$a7,$4f,$57,$5f,$17,$a9,$ac,$ac,$b4,$b5,$b7,$d7,$f3
.byte $95,$55,$55,$95,$95,$95,$95,$95,$55,$55,$55,$55,$55,$55,$55,$55
.byte $ff,$ff,$ff,$fe,$fa,$fe,$fe,$fa,$fe,$fe,$ee,$ee,$ae,$af,$af,$9f
.byte $eb,$4d,$4f,$9f,$b7,$b7,$3b,$fb,$80,$80,$83,$83,$43,$41,$4f,$4c
.byte $f7,$fe,$de,$7c,$fa,$fa,$f0,$70,$82,$80,$00,$30,$30,$00,$00,$c0
.byte $08,$82,$00,$03,$0f,$3d,$3d,$8f,$05,$fe,$36,$1a,$94,$90,$93,$1c
.byte $f1,$c0,$f4,$fc,$3f,$0f,$2a,$ab,$c8,$08,$3c,$ac,$c4,$c4,$f9,$d1
.byte $fa,$2b,$af,$bc,$34,$77,$b7,$c7,$30,$c3,$1b,$2b,$6b,$f7,$d7,$ed
.byte $01,$00,$08,$02,$8f,$0f,$87,$cc,$4b,$2e,$af,$fe,$fb,$ff,$ee,$bf
.byte $b3,$ac,$f3,$c3,$20,$bf,$ff,$bf,$20,$23,$00,$83,$00,$cc,$ef,$ff
.byte $ff,$3f,$af,$ef,$bf,$ff,$ff,$ff,$ef,$fa,$fe,$fd,$ff,$ff,$ff,$ff
.byte $c3,$c0,$bc,$8f,$fa,$fa,$fa,$fe,$b1,$28,$82,$cc,$f0,$5c,$50,$fc
.byte $40,$80,$23,$17,$17,$a5,$67,$31,$de,$fd,$aa,$21,$0f,$b5,$61,$58
.byte $fd,$ff,$c3,$2f,$2f,$04,$40,$aa,$05,$51,$b3,$91,$ad,$fc,$fc,$ff
.byte $7a,$55,$5c,$56,$56,$f3,$3e,$3f,$bf,$ff,$aa,$5c,$7f,$ff,$7f,$a4
.byte $cb,$83,$a1,$a2,$b8,$3b,$3f,$3f,$bf,$bf,$bf,$ff,$ff,$ff,$ff,$ff
.byte $f5,$dd,$7e,$7e,$fa,$ee,$fd,$dd,$af,$ae,$ff,$7f,$7f,$7f,$ff,$bd
.byte $ff,$7e,$f7,$fa,$fa,$e9,$f9,$5d,$ff,$bf,$f6,$ea,$b5,$7a,$5e,$95
.byte $ff,$fd,$fb,$e9,$6e,$55,$a5,$a6,$d0,$37,$37,$a4,$aa,$ff,$af,$aa
.byte $ff,$ff,$ff,$bf,$7f,$7f,$f9,$af,$ea,$f9,$fa,$f9,$fc,$fe,$fe,$d6
.byte $ab,$9b,$af,$bf,$7f,$bf,$ff,$ff,$f8,$fe,$fe,$fe,$fe,$fd,$f9,$e1
.byte $95,$95,$95,$95,$55,$a5,$a5,$a9,$55,$55,$55,$55,$55,$55,$55,$55
.byte $fb,$fb,$fb,$ff,$ff,$fd,$f9,$fe,$de,$9e,$de,$fe,$6f,$67,$e7,$b5
.byte $fb,$f3,$f7,$ff,$bf,$bf,$b7,$37,$4f,$6c,$68,$6c,$f0,$f0,$f0,$fc
.byte $1c,$2c,$af,$9f,$9e,$9d,$a4,$57,$00,$20,$2c,$ad,$8d,$2a,$23,$cf
.byte $28,$e0,$90,$80,$01,$0c,$02,$27,$02,$13,$4f,$3f,$be,$ea,$e1,$a3
.byte $57,$43,$43,$0c,$7e,$3e,$7e,$f4,$ff,$fc,$fd,$f1,$e8,$c8,$d0,$01
.byte $08,$e0,$79,$41,$71,$31,$f4,$f0,$7f,$f3,$1f,$38,$38,$3f,$9f,$0f
.byte $8f,$bf,$fe,$7e,$54,$f0,$bf,$ab,$3a,$7e,$6c,$5e,$46,$06,$02,$fe
.byte $bf,$eb,$fe,$fe,$bf,$58,$56,$56,$ff,$ff,$ef,$ff,$ff,$ff,$3f,$8f
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$bf,$ff,$ff,$ff,$ff,$fb,$ff,$fb,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$bf,$b0,$ff,$ff,$ff,$fe,$ff,$ff,$ff
.byte $30,$fc,$d8,$e8,$d0,$74,$de,$da,$1b,$8b,$17,$09,$2e,$3e,$b8,$c8
.byte $c3,$fc,$3a,$fd,$9f,$7f,$ff,$ff,$73,$f3,$3f,$ab,$ff,$ff,$fe,$ff
.byte $0c,$fc,$fd,$eb,$ee,$fa,$ba,$ae,$cc,$cc,$03,$f0,$ef,$fe,$aa,$55
.byte $c3,$ff,$ef,$ff,$ff,$ab,$a5,$6b,$3f,$ff,$ff,$ff,$ff,$fb,$fe,$7f
.byte $da,$d5,$d6,$e6,$ca,$fe,$fe,$3f,$94,$bd,$7f,$ff,$e7,$e9,$ea,$fe
.byte $fe,$fe,$da,$5f,$df,$df,$e7,$af,$6b,$eb,$29,$3f,$c8,$c0,$c0,$f7
.byte $ff,$af,$ad,$ac,$61,$40,$28,$98,$ff,$ff,$6f,$6f,$6e,$aa,$4a,$08
.byte $ff,$ef,$fb,$fe,$d6,$e5,$85,$7e,$4c,$ff,$b4,$74,$76,$6e,$4e,$84
.byte $aa,$f6,$fa,$77,$06,$3d,$3c,$15,$ff,$ee,$bf,$ff,$b2,$e3,$e1,$f1
.byte $f5,$7d,$7d,$fd,$75,$fd,$fd,$fd,$55,$95,$95,$95,$55,$55,$55,$55
.byte $f9,$fb,$fb,$f7,$ff,$fe,$ff,$ff,$bf,$bf,$bb,$bb,$bb,$ab,$ab,$ab
.byte $f7,$f2,$d2,$d9,$98,$98,$78,$24,$f0,$32,$02,$70,$03,$4c,$42,$a0
.byte $f5,$be,$3f,$2f,$eb,$0a,$fe,$0b,$c3,$fc,$5a,$95,$59,$6e,$6e,$61
.byte $c6,$07,$44,$4c,$4c,$c0,$40,$01,$03,$03,$0e,$0e,$0e,$05,$04,$0d
.byte $57,$5c,$70,$70,$4b,$c3,$80,$0c,$4f,$2b,$eb,$a9,$bc,$00,$30,$31
.byte $ca,$ea,$aa,$9a,$c9,$ab,$ec,$fc,$41,$c0,$e0,$48,$6a,$c3,$0f,$0f
.byte $59,$a5,$3a,$f9,$3b,$fb,$c2,$e8,$10,$d4,$f4,$ff,$cf,$8f,$a3,$aa
.byte $1f,$05,$11,$40,$42,$fa,$fb,$f8,$55,$ad,$4c,$b0,$a8,$8a,$01,$0c
.byte $7f,$ff,$f3,$34,$41,$0a,$a8,$a0,$ff,$ff,$ff,$ff,$ff,$7f,$95,$2a
.byte $ff,$ff,$ff,$fd,$f6,$5a,$aa,$aa,$55,$57,$6f,$bb,$fa,$a8,$83,$1a
.byte $fa,$ed,$b0,$c3,$0b,$ef,$ad,$f5,$ea,$3a,$5b,$5e,$7e,$fd,$f7,$5e
.byte $ac,$ab,$ec,$7f,$55,$65,$b7,$ea,$eb,$df,$6f,$be,$a9,$56,$a6,$eb
.byte $fe,$db,$5b,$5a,$ff,$ef,$bf,$bf,$ff,$ff,$ff,$aa,$af,$f7,$ff,$ff
.byte $aa,$56,$66,$aa,$ff,$ff,$ff,$ff,$9a,$a6,$b5,$a9,$be,$fe,$ff,$ff
.byte $bf,$e3,$cf,$f3,$5f,$7c,$73,$50,$fa,$ff,$ff,$ff,$ff,$7f,$3f,$3f
.byte $ab,$aa,$ba,$bc,$7f,$7f,$5a,$5a,$eb,$3b,$b7,$bb,$a5,$20,$10,$dc
.byte $7c,$57,$ae,$eb,$bf,$6b,$5a,$6b,$03,$f3,$fb,$bf,$fb,$fe,$f3,$fc
.byte $09,$c1,$c3,$ff,$ff,$5f,$3f,$fa,$09,$4d,$fd,$3f,$3f,$ab,$ea,$eb
.byte $00,$40,$01,$11,$d1,$d7,$d6,$d6,$50,$63,$8b,$03,$22,$f9,$f9,$f6
.byte $ff,$ff,$ff,$ff,$fd,$ff,$bf,$ae,$af,$bf,$bf,$bb,$ff,$ae,$ab,$a8
.byte $fe,$fe,$fe,$ef,$bf,$bf,$8b,$1a,$fd,$fd,$fd,$de,$de,$ee,$5e,$7a
.byte $2b,$ef,$6e,$9e,$c0,$c0,$0c,$c3,$a0,$33,$40,$02,$02,$3a,$33,$f2
.byte $1a,$0b,$4f,$1f,$de,$df,$df,$da,$e4,$f0,$f4,$f0,$f8,$fc,$f8,$f9
.byte $31,$30,$03,$04,$37,$07,$34,$00,$06,$00,$00,$20,$00,$a1,$85,$ad
.byte $04,$33,$cf,$ff,$ab,$9b,$53,$d3,$0a,$09,$09,$44,$6e,$6e,$17,$7d
.byte $18,$f1,$f0,$f0,$13,$bf,$fc,$e0,$bf,$33,$ce,$fc,$7f,$ff,$cf,$3d
.byte $0f,$2e,$8c,$f2,$81,$a9,$a5,$54,$2a,$86,$02,$f7,$ff,$ff,$f4,$29
.byte $e8,$fb,$be,$9c,$9b,$a7,$95,$9a,$fd,$3f,$f3,$43,$2a,$0a,$1a,$54
.byte $7e,$3f,$3e,$3b,$f5,$d5,$51,$55,$29,$49,$4a,$a0,$b9,$39,$3d,$ff
.byte $f0,$c3,$1f,$7f,$fe,$ea,$95,$95,$aa,$af,$af,$ff,$ff,$ff,$d5,$d5
.byte $a9,$a5,$5f,$6f,$bf,$ff,$fe,$ea,$f5,$ff,$5f,$df,$7b,$eb,$fe,$ba
.byte $df,$7f,$fb,$fe,$fe,$ee,$be,$aa,$6f,$eb,$ff,$ef,$bb,$ff,$fe,$ff
.byte $6a,$7e,$ff,$bf,$ff,$ff,$ff,$ff,$fe,$fe,$fe,$fe,$fe,$ff,$ff,$ff
.byte $be,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fe,$ff,$ff,$ff,$ff,$ff,$ff
.byte $9c,$ec,$ef,$ec,$ef,$6f,$dc,$50,$3f,$3f,$36,$0f,$02,$03,$cf,$0f
.byte $fe,$ff,$ef,$ea,$ea,$fb,$e9,$f3,$60,$67,$53,$11,$31,$30,$04,$00
.byte $f5,$ff,$ff,$fe,$6b,$83,$2a,$0d,$f3,$52,$5c,$40,$48,$83,$40,$56
.byte $01,$37,$0f,$1f,$5a,$6a,$66,$6a,$a7,$a7,$a7,$7f,$3f,$0f,$0c,$42
.byte $53,$43,$43,$43,$72,$fa,$a8,$a9,$97,$9f,$d3,$4f,$4f,$fc,$3e,$cc
.byte $ff,$ef,$ab,$ab,$cf,$47,$07,$00,$bd,$bd,$ac,$a8,$fc,$fc,$fc,$3f
.byte $1a,$02,$f0,$cd,$00,$c4,$1a,$ca,$67,$2f,$5f,$af,$1f,$33,$b7,$f7
.byte $c0,$f0,$f0,$f0,$f4,$f2,$e2,$62,$2f,$2f,$1f,$1f,$1f,$d3,$23,$c3
.byte $1b,$1b,$1b,$1b,$2b,$6f,$2c,$2c,$aa,$ef,$c9,$f1,$c4,$f0,$80,$80
.byte $0a,$4f,$5f,$7f,$6f,$6f,$6b,$23,$55,$fe,$ff,$fe,$fa,$fe,$fa,$fe
.byte $e4,$b6,$b7,$b7,$bf,$bf,$bf,$bf,$29,$15,$fc,$ff,$bf,$be,$aa,$bd
.byte $29,$1b,$26,$67,$65,$6d,$7f,$4b,$ff,$7f,$7f,$ef,$e9,$e8,$f4,$50
.byte $5f,$5f,$60,$f0,$bb,$b3,$fa,$08,$70,$00,$00,$f3,$7b,$c0,$0c,$aa
.byte $ab,$0f,$32,$fd,$13,$03,$3f,$aa,$5f,$a9,$da,$fb,$d9,$da,$fa,$aa
.byte $05,$55,$fd,$ff,$fe,$fa,$ab,$bd,$2f,$ff,$af,$bf,$ff,$e7,$bf,$55
.byte $ff,$d5,$db,$7f,$ff,$be,$aa,$aa,$56,$97,$bf,$ab,$bf,$af,$ff,$ff
.byte $ee,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ab,$fe,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$bf,$ef,$fb,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fb,$d7,$06
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$fe,$fa,$ff,$f9,$f9,$f5,$d6,$5a,$6a,$95
.byte $b0,$bf,$af,$ac,$d4,$91,$51,$d3,$83,$cf,$cd,$81,$ed,$4d,$4d,$8d
.byte $30,$30,$31,$fe,$d1,$fe,$f3,$ee,$c8,$a0,$84,$c5,$d1,$f1,$7f,$ff
.byte $0e,$01,$31,$35,$d5,$f5,$00,$c3,$7c,$ca,$78,$5c,$5c,$7c,$7f,$fb
.byte $8f,$8a,$aa,$aa,$03,$c3,$7f,$53,$6a,$69,$6b,$4f,$70,$40,$4f,$3f
.byte $42,$02,$38,$e0,$cc,$30,$c0,$b0,$2c,$87,$bf,$0d,$23,$c8,$c3,$d3
.byte $ff,$fc,$cc,$0f,$b0,$00,$85,$86,$c0,$ff,$f3,$f3,$30,$00,$6a,$aa
.byte $0e,$d2,$0e,$0e,$0f,$3f,$3e,$3e,$86,$07,$07,$2f,$9f,$52,$60,$60
.byte $b3,$f3,$f3,$33,$0f,$0f,$0f,$3f,$cf,$cf,$ce,$fe,$fa,$fa,$ea,$e9
.byte $2c,$8d,$bf,$bf,$ea,$e2,$21,$20,$c3,$00,$81,$88,$3b,$3b,$fb,$fb
.byte $01,$09,$85,$46,$c0,$e0,$e0,$cf,$af,$af,$3f,$3f,$0f,$0b,$3f,$d5
.byte $6f,$7f,$7f,$7f,$3f,$3a,$3a,$3b,$fc,$e0,$c0,$c8,$cc,$4c,$44,$44
.byte $66,$6b,$7f,$4e,$78,$6c,$80,$80,$e4,$50,$70,$1f,$0f,$3e,$fa,$fa
.byte $2a,$2e,$e5,$96,$5f,$7f,$ff,$ee,$ed,$57,$ef,$fb,$be,$eb,$aa,$ea
.byte $ff,$ff,$fe,$ef,$ab,$ff,$95,$7f,$ff,$ff,$5e,$5b,$df,$7f,$bb,$be
.byte $af,$9f,$a7,$69,$9b,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$bf,$ef,$fb,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$f6,$e9,$ff,$ff,$f5,$df,$fe,$6a,$9a,$6a
.byte $a9,$a5,$55,$6a,$ff,$5f,$df,$cf,$fb,$73,$d3,$f3,$fb,$fa,$f8,$f0
.byte $ff,$be,$fd,$ad,$aa,$56,$42,$05,$fc,$ba,$7a,$fc,$a8,$bc,$b0,$88
.byte $ff,$ff,$ff,$aa,$a9,$29,$a9,$3a,$aa,$ab,$ff,$fd,$fd,$b7,$ff,$20
.byte $eb,$a9,$25,$a6,$65,$bf,$cc,$33,$ea,$6a,$3a,$b3,$8c,$70,$04,$c5
.byte $f7,$f4,$f0,$30,$27,$32,$3e,$e6,$c9,$ea,$bc,$8f,$3f,$ff,$ff,$ff
.byte $5a,$5a,$5a,$35,$73,$3f,$ff,$ff,$fa,$fb,$ff,$bf,$7f,$5b,$95,$91
.byte $4e,$40,$89,$aa,$b6,$3e,$fe,$ff,$a8,$2a,$8a,$fa,$fa,$f0,$7f,$7f
.byte $3f,$ff,$fb,$ff,$ff,$ff,$b7,$b7,$fc,$bc,$20,$e0,$a0,$a3,$ab,$ab
.byte $83,$04,$0a,$33,$0c,$ff,$f0,$fc,$2e,$20,$ff,$fb,$3c,$ff,$eb,$aa
.byte $86,$86,$04,$04,$00,$0f,$0f,$cf,$ff,$f7,$f7,$f7,$37,$9a,$9a,$9a
.byte $3d,$3d,$3d,$3d,$3d,$0f,$2e,$ae,$a0,$52,$d2,$c2,$1e,$de,$d2,$c2
.byte $82,$81,$8b,$8f,$0d,$05,$06,$42,$ab,$af,$af,$bf,$7f,$df,$57,$97
.byte $23,$0b,$4b,$8b,$03,$03,$03,$3b,$fb,$f3,$33,$0b,$03,$03,$03,$03
.byte $cf,$cf,$c3,$c3,$c2,$8b,$cd,$a5,$3f,$3f,$2f,$3f,$3f,$bf,$5a,$5a
.byte $04,$0e,$39,$be,$be,$ae,$af,$f5,$6f,$67,$ef,$6f,$af,$8f,$8f,$47
.byte $aa,$bf,$8d,$8d,$ff,$ef,$fe,$ff,$7f,$7f,$6f,$ef,$6f,$fb,$fb,$ca
.byte $bb,$fe,$ff,$ee,$ef,$ff,$fe,$ff,$56,$aa,$a6,$e6,$db,$ff,$7f,$ff
.byte $fa,$ff,$ff,$ff,$fd,$ed,$b4,$bd,$ef,$ff,$ff,$ff,$5f,$af,$8f,$05
.byte $ff,$ff,$ff,$ff,$fe,$f6,$f8,$e8,$57,$5f,$7c,$f2,$ea,$af,$2f,$83
.byte $fa,$bf,$bf,$3f,$2d,$6a,$d8,$db,$bf,$af,$fa,$48,$4a,$30,$d4,$f7
.byte $ea,$e2,$3d,$35,$ff,$b5,$a2,$30,$eb,$bd,$3d,$7d,$6f,$e2,$3e,$2a
.byte $ff,$bf,$9b,$9d,$9d,$bf,$7c,$fc,$c0,$b4,$fd,$fd,$fd,$2f,$c0,$0e
.byte $80,$2b,$8c,$4c,$fb,$a3,$e2,$f0,$e0,$01,$fe,$fe,$28,$20,$3f,$ff
.byte $0b,$f2,$8a,$a2,$2c,$3f,$ff,$f3,$ea,$a3,$fa,$cf,$3f,$ff,$fb,$e3
.byte $e3,$8c,$3f,$ff,$ee,$bb,$0f,$fc,$03,$00,$2c,$20,$3c,$c2,$d0,$91
.byte $ff,$ff,$0f,$03,$c0,$00,$f0,$c0,$f0,$fe,$fe,$ff,$33,$c3,$03,$30
.byte $cf,$0f,$ff,$ff,$ff,$ff,$ff,$ff,$7f,$5f,$df,$db,$da,$db,$d3,$df
.byte $bf,$8f,$ad,$af,$ad,$ad,$ac,$ad,$ff,$fe,$fe,$fe,$fe,$7f,$ff,$ff
.byte $f3,$f3,$ff,$fc,$a3,$ef,$c3,$cc,$cf,$3f,$3f,$3f,$ff,$ff,$fb,$8b
.byte $0f,$0f,$0f,$3f,$3f,$3f,$3f,$0f,$eb,$d9,$fa,$f6,$fe,$fc,$ff,$ff
.byte $f3,$f0,$fc,$f6,$8e,$8c,$6f,$11,$95,$75,$f5,$f5,$f0,$60,$c0,$42
.byte $83,$83,$01,$03,$02,$07,$0b,$09,$f6,$f6,$fe,$f6,$f6,$f6,$f4,$f6
.byte $33,$4f,$ff,$c3,$f0,$f3,$f3,$f0,$cc,$dc,$d0,$ec,$ec,$23,$ef,$e3
.byte $65,$a5,$00,$03,$1f,$2f,$f4,$fb,$e4,$d4,$3b,$7e,$ff,$ff,$15,$01
.byte $fa,$fa,$ff,$8d,$d1,$10,$0b,$3b,$87,$87,$40,$38,$fe,$fa,$fb,$7d
.byte $ff,$ff,$ff,$0f,$cf,$83,$00,$e9,$c2,$83,$8b,$bb,$9c,$8c,$14,$14
.byte $bf,$bf,$eb,$fa,$17,$0e,$12,$12,$ff,$ff,$f3,$73,$93,$60,$a0,$ac
.byte $56,$aa,$aa,$ab,$ff,$bf,$ff,$bf,$ce,$81,$b2,$7f,$ab,$bb,$7f,$7f
.byte $fd,$f1,$bd,$c9,$bd,$2d,$f1,$f9,$0b,$43,$c3,$f6,$f7,$c0,$c8,$e0
.byte $92,$33,$be,$3f,$c9,$29,$b4,$25,$56,$56,$27,$5c,$6c,$b3,$c0,$c0
.byte $61,$1d,$f0,$45,$3c,$fe,$2a,$ab,$74,$31,$ff,$fe,$ab,$ba,$ba,$ea
.byte $f3,$fc,$ff,$6b,$fe,$aa,$ab,$aa,$d0,$c0,$c7,$f7,$bf,$af,$af,$bb
.byte $bd,$f5,$f5,$b7,$a3,$88,$80,$80,$ce,$a2,$bf,$3f,$80,$cc,$4f,$4f
.byte $88,$ff,$ff,$c0,$80,$ff,$f3,$08,$ff,$ff,$ec,$03,$ff,$fe,$b2,$cf
.byte $f3,$e3,$bf,$ff,$ee,$e3,$3f,$ff,$b1,$f2,$c0,$03,$73,$f5,$f5,$c5
.byte $43,$73,$30,$20,$e2,$b8,$43,$0f,$c0,$ce,$eb,$ff,$3f,$ff,$f3,$cc
.byte $0f,$0f,$cf,$fc,$fc,$fe,$f9,$d6,$df,$d3,$cf,$83,$83,$4f,$0f,$0f
.byte $f2,$fe,$fe,$fe,$fd,$fe,$fe,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$fb,$bb,$b3,$bf,$bf,$bf,$bf,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$f0
.byte $33,$03,$33,$03,$3c,$0f,$3f,$03,$cf,$f3,$c0,$33,$0f,$00,$cf,$33
.byte $d9,$c2,$fd,$03,$f3,$3c,$33,$f3,$9c,$13,$d8,$27,$f4,$3a,$3e,$3e
.byte $09,$09,$39,$c9,$f8,$c8,$40,$70,$a4,$bc,$f9,$fd,$fa,$7f,$3f,$3f
.byte $f0,$f3,$f0,$33,$3f,$4c,$a3,$ab,$23,$1c,$00,$f0,$f0,$fc,$fc,$ff
.byte $fe,$fd,$ff,$cf,$00,$0c,$4c,$bd,$31,$8d,$2c,$e3,$c8,$f2,$4c,$53
.byte $ff,$ff,$ff,$85,$85,$21,$28,$e8,$ca,$b7,$fd,$fd,$f7,$f7,$2a,$0a
.byte $1a,$f1,$7d,$3f,$83,$4b,$56,$f2,$d2,$1a,$ba,$fa,$fa,$f7,$ff,$30
.byte $62,$a0,$a7,$ab,$a7,$a6,$55,$37,$d2,$ae,$9f,$d7,$f7,$77,$17,$91
.byte $15,$ff,$3f,$0c,$43,$aa,$a5,$5f,$ff,$ff,$cf,$8f,$55,$5d,$a1,$ab
.byte $f7,$f7,$f4,$39,$f9,$be,$ae,$af,$a4,$a5,$78,$78,$79,$01,$0c,$bd
.byte $d4,$9f,$f4,$d2,$d0,$5f,$5c,$d3,$3f,$0d,$0e,$fa,$fa,$ca,$fa,$f6
.byte $f4,$f5,$fe,$7a,$7b,$ef,$fb,$f0,$6e,$6b,$7a,$da,$bf,$a7,$ff,$6e
.byte $ff,$ff,$bf,$ef,$eb,$e9,$e5,$a9,$7a,$af,$6d,$99,$b9,$7a,$6f,$7c
.byte $41,$b9,$ac,$ad,$ec,$ec,$45,$45,$8f,$8c,$5c,$3c,$2f,$a3,$80,$88
.byte $cf,$ff,$3c,$cd,$38,$3f,$fc,$30,$ff,$fc,$ae,$03,$3f,$7f,$00,$00
.byte $33,$b3,$ff,$f3,$c0,$00,$03,$00,$eb,$f3,$f3,$c0,$f0,$3c,$00,$fc
.byte $3f,$fc,$ff,$ff,$ff,$3c,$fd,$c2,$0c,$3f,$fd,$35,$e9,$29,$a4,$90
.byte $28,$68,$63,$40,$00,$30,$00,$03,$0f,$ff,$3f,$ff,$ff,$3f,$ff,$ff
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$7f,$e8,$cf,$0f,$a3,$af,$88
.byte $8f,$ef,$af,$bf,$af,$bf,$af,$af,$ff,$ff,$ff,$ff,$3c,$cc,$cc,$cf
.byte $cf,$cf,$cc,$c3,$3f,$0f,$cc,$3c,$c3,$f3,$03,$33,$fc,$33,$c3,$ff
.byte $c7,$3b,$cb,$fb,$fb,$fb,$fb,$3b,$ff,$3f,$3f,$7f,$7f,$bf,$bf,$bf
.byte $1f,$9f,$e7,$e7,$f9,$fa,$fe,$fe,$05,$cd,$f3,$ff,$3f,$1f,$1c,$82
.byte $fd,$ff,$bf,$bf,$1f,$87,$8e,$86,$01,$c1,$f9,$ff,$ff,$ff,$af,$aa
.byte $21,$82,$0a,$da,$ff,$ff,$ff,$5f,$06,$1a,$48,$48,$ff,$ff,$ff,$ff
.byte $ea,$ca,$02,$02,$d6,$ff,$ff,$ff,$00,$dc,$f7,$ff,$cf,$a4,$aa,$aa
.byte $ff,$3f,$3f,$7f,$bd,$a0,$a4,$aa,$1a,$de,$d6,$fa,$f4,$20,$20,$50
.byte $34,$fb,$fb,$cb,$fb,$c8,$30,$00,$04,$c4,$f7,$f4,$f4,$f7,$fb,$cf
.byte $0a,$fc,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$31,$ce,$fe,$fe,$ff,$f6,$69
.byte $3e,$3e,$3f,$3f,$bf,$bd,$f6,$de,$82,$02,$c0,$e8,$fe,$d6,$de,$16
.byte $8f,$40,$5f,$5e,$55,$9b,$db,$bf,$eb,$af,$be,$ff,$7f,$ff,$7f,$2a
.byte $5f,$9c,$6f,$6a,$0c,$b3,$5a,$55,$ea,$aa,$fe,$ff,$0c,$5d,$f7,$bd
.byte $aa,$aa,$b3,$f3,$ed,$23,$2f,$7f,$73,$fb,$02,$8f,$3b,$cf,$fe,$f8
.byte $3b,$7c,$1c,$3c,$08,$40,$60,$68,$ec,$f3,$3c,$8c,$fc,$c0,$c0,$00
.byte $00,$c0,$00,$00,$00,$cc,$0f,$0f,$00,$00,$00,$02,$af,$be,$32,$00
.byte $00,$00,$00,$f5,$ff,$f2,$da,$aa,$28,$2a,$81,$07,$ff,$fd,$fc,$c0
.byte $05,$3d,$f7,$f0,$48,$02,$a8,$00,$40,$a3,$83,$8f,$c3,$cc,$fc,$f0
.byte $30,$3c,$3c,$0c,$ea,$02,$00,$f3,$cc,$cf,$3f,$3f,$03,$00,$00,$00
.byte $ff,$cf,$ff,$ff,$ff,$03,$0f,$0f,$e0,$c2,$fc,$fc,$ff,$f3,$f3,$f0
.byte $af,$ff,$ff,$3f,$ff,$ff,$fb,$ff,$cf,$f0,$f0,$f0,$f3,$f0,$fc,$fc
.byte $33,$3f,$3c,$c3,$cc,$33,$3c,$fc,$3f,$ff,$ff,$3c,$3f,$fc,$3c,$cf
.byte $fb,$fb,$fb,$fb,$cb,$f8,$f8,$00,$7f,$7f,$7f,$7f,$43,$d2,$06,$1a
.byte $aa,$a8,$a5,$95,$ff,$ff,$ff,$fe,$fd,$bd,$bf,$6f,$ab,$c3,$03,$00
.byte $79,$59,$5b,$ff,$ff,$fa,$ae,$fe,$25,$ed,$af,$ab,$ff,$ff,$ff,$ff
.byte $aa,$69,$a9,$ff,$ff,$ff,$ff,$ff,$bd,$ab,$ab,$bd,$ef,$fd,$ff,$f6
.byte $bf,$17,$55,$b5,$1a,$fe,$ff,$bb,$ff,$ff,$e9,$ea,$ea,$af,$d4,$5e
.byte $ff,$ff,$ff,$bd,$bb,$bb,$99,$21,$ff,$ff,$ff,$55,$a6,$e6,$a6,$e7
.byte $94,$aa,$aa,$aa,$ff,$ff,$bf,$ef,$55,$aa,$aa,$ab,$ff,$fb,$ff,$bc
.byte $2a,$aa,$a5,$55,$fd,$ff,$ff,$2f,$a5,$5f,$ff,$57,$ff,$ff,$ff,$bf
.byte $aa,$ea,$fe,$ff,$fd,$fd,$f9,$fd,$19,$a9,$fd,$f5,$fd,$ae,$ff,$f7
.byte $fc,$bd,$81,$f0,$f0,$a1,$ae,$aa,$3a,$fc,$ff,$3f,$0f,$03,$63,$66
.byte $aa,$c2,$ff,$ff,$ff,$ff,$00,$55,$aa,$ab,$23,$ff,$ff,$ff,$08,$55
.byte $2c,$0c,$cf,$cf,$ef,$2f,$2a,$aa,$5f,$ff,$ff,$c0,$f3,$f2,$a5,$a1
.byte $7f,$7c,$77,$43,$34,$a6,$aa,$6a,$00,$20,$20,$83,$ff,$ff,$ff,$dc
.byte $02,$53,$3c,$ff,$f5,$fe,$ca,$00,$f6,$aa,$aa,$62,$13,$3f,$3f,$c3
.byte $aa,$a8,$9c,$0c,$13,$0f,$3c,$f3,$8c,$03,$03,$03,$f3,$f0,$cc,$0c
.byte $22,$28,$a8,$a3,$a3,$3c,$f0,$c3,$0c,$00,$03,$03,$03,$02,$00,$03
.byte $0c,$08,$03,$b0,$20,$00,$00,$00,$00,$00,$0c,$03,$03,$30,$c3,$f3
.byte $cf,$0f,$0f,$03,$03,$0f,$0f,$cf,$ff,$ff,$3c,$3e,$3c,$3c,$0c,$0f
.byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$3f,$ff,$fc,$fc,$ff,$ff,$fc,$fc,$fc
.byte $00,$cf,$0c,$33,$fc,$f0,$ff,$3f,$34,$33,$3c,$30,$c3,$f0,$0e,$0a
.byte $00,$13,$0a,$3b,$fb,$ba,$ff,$fc,$6a,$a9,$a9,$64,$9c,$4f,$cf,$ff
.byte $af,$4c,$ff,$c3,$ff,$ff,$fc,$fc,$33,$ff,$ff,$fd,$c6,$da,$1a,$4a
.byte $0f,$07,$3b,$bb,$9a,$f7,$f9,$f7,$dd,$ff,$5b,$5f,$ff,$eb,$ee,$bb
.byte $ff,$fb,$7f,$bf,$ff,$fa,$fb,$fe,$5f,$ff,$fe,$7e,$ab,$6e,$6a,$ff
.byte $ff,$ff,$f9,$fd,$b5,$eb,$aa,$ea,$ab,$af,$bf,$ff,$af,$7f,$7f,$7c
.byte $55,$a9,$a0,$8c,$bc,$0f,$3f,$ff,$ff,$fb,$ef,$0a,$53,$10,$10,$13
.byte $9e,$66,$7f,$fe,$eb,$fb,$3f,$ef,$ff,$fe,$b2,$a0,$91,$80,$48,$a0
.byte $15,$5f,$cc,$0f,$f0,$00,$88,$2a,$55,$92,$e2,$cc,$3f,$3f,$3f,$0f
.byte $56,$aa,$82,$0c,$ff,$ff,$ff,$ff,$fd,$ff,$3f,$3f,$a3,$82,$8a,$aa
.byte $57,$fd,$f0,$f0,$c0,$88,$aa,$aa,$ff,$af,$0f,$0a,$4a,$08,$10,$51
.byte $4f,$55,$ff,$03,$23,$20,$00,$02,$5f,$ff,$fd,$00,$c2,$c8,$08,$00
.byte $d9,$a5,$9e,$3b,$00,$00,$00,$00,$f6,$fd,$a6,$00,$00,$00,$00,$00
.byte $ff,$22,$08,$81,$00,$40,$00,$40,$44,$1a,$08,$c2,$f0,$31,$00,$cc
.byte $00,$03,$ff,$f3,$3f,$af,$0c,$0f,$33,$0f,$cf,$03,$c0,$f0,$00,$3c
.byte $fc,$cf,$3c,$0c,$13,$00,$0a,$c8,$f0,$c0,$03,$23,$22,$00,$00,$01
.byte $0f,$03,$40,$42,$00,$00,$0b,$b3,$0f,$00,$0c,$ff,$3a,$02,$c0,$f3
.byte $00,$00,$00,$c3,$c0,$f0,$f2,$f0,$0c,$3f,$3f,$8f,$0f,$c3,$0c,$30
.byte $3f,$3f,$cf,$ce,$ff,$ff,$ff,$ff,$c3,$f0,$c0,$fc,$f0,$c3,$00,$f0
.byte $3f,$3f,$3f,$3f,$03,$22,$23,$22,$fc,$ff,$ff,$ff,$ff,$fc,$ff,$bc



; CharSet Attribute (L1) Data...
; 1000 attributes, 1 attribute per image, 8 bits per attribute, total size is 1000 ($3e8) bytes.
; nb. Upper nybbles = material, lower nybbles = colour (colour matrix low).

* = addr_charset_attrib_L1_data
charset_attrib_L1_data

.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0b,$07,$00,$00
.byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0c,$07,$07,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$0b,$00,$00,$00,$00,$00,$00
.byte $0b,$0b,$0b,$0b,$0b,$0b,$07,$0b,$0b,$0b,$0b,$0b,$0b,$07,$0a,$07
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $0b,$0b,$07,$01,$00,$0b,$0b,$0b,$0b,$01,$01,$01,$0a,$01,$01,$01
.byte $01,$07,$0a,$0a,$07,$0a,$01,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$01,$01,$01,$01,$01,$01,$01
.byte $01,$01,$01,$07,$07,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01
.byte $0b,$0b,$00,$00,$00,$00,$00,$00,$00,$0b,$0b,$00,$00,$00,$00,$00
.byte $00,$01,$01,$01,$01,$01,$01,$01,$07,$01,$01,$07,$07,$01,$01,$01
.byte $01,$01,$01,$01,$01,$01,$01,$01,$0b,$0b,$0b,$0b,$0b,$0b,$00,$00
.byte $00,$00,$0a,$00,$00,$00,$00,$00,$00,$01,$01,$01,$07,$01,$01,$07
.byte $01,$07,$07,$01,$07,$07,$0a,$0a,$07,$01,$01,$0b,$01,$0b,$01,$0b
.byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0c,$0b,$07,$07,$00,$00,$00,$00,$00
.byte $07,$00,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$07,$0a,$07,$0a
.byte $08,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$01,$0b,$0b,$0b,$01,$0b,$0c,$0b
.byte $01,$01,$07,$00,$00,$01,$00,$00,$07,$07,$07,$07,$07,$07,$07,$07
.byte $07,$07,$0a,$0b,$0b,$0b,$07,$07,$00,$08,$0b,$0a,$0a,$0b,$0b,$0b
.byte $01,$01,$0b,$01,$01,$01,$0b,$0b,$0a,$01,$07,$00,$00,$01,$00,$00
.byte $07,$08,$08,$07,$07,$07,$07,$07,$08,$08,$0b,$0b,$0b,$0b,$00,$08
.byte $02,$00,$00,$0b,$08,$0b,$00,$01,$01,$0b,$0b,$01,$0b,$01,$0c,$0b
.byte $01,$01,$07,$00,$00,$00,$01,$00,$0b,$02,$02,$02,$02,$07,$08,$08
.byte $02,$08,$08,$00,$00,$00,$0a,$0a,$08,$08,$00,$00,$00,$08,$00,$01
.byte $01,$0b,$00,$0b,$01,$0b,$08,$0b,$01,$01,$07,$08,$0c,$01,$0b,$00
.byte $0b,$02,$02,$02,$02,$07,$00,$00,$00,$00,$00,$0b,$0b,$0b,$0a,$00
.byte $00,$00,$02,$00,$00,$08,$02,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$08,$0b
.byte $0b,$0c,$08,$0c,$0c,$0c,$0b,$0b,$00,$02,$02,$07,$07,$08,$0a,$0a
.byte $0b,$08,$00,$00,$00,$08,$0a,$0a,$07,$07,$0b,$0b,$00,$0b,$08,$0b
.byte $0b,$0b,$0b,$0b,$0b,$00,$0b,$00,$0b,$00,$0c,$0c,$0c,$0b,$0b,$07
.byte $00,$00,$07,$0a,$07,$00,$08,$0a,$08,$08,$00,$07,$07,$07,$08,$08
.byte $0b,$0b,$0b,$0b,$0f,$00,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b
.byte $0b,$0b,$0b,$0b,$0b,$0a,$07,$0a,$07,$07,$07,$0a,$07,$08,$08,$08
.byte $0f,$00,$08,$02,$08,$08,$0c,$0c,$0b,$0b,$0b,$0b,$0b,$0b,$0a,$00
.byte $0f,$0b,$0b,$0f,$00,$0b,$0b,$0b,$0b,$0b,$0b,$0c,$0b,$0b,$0f,$0f
.byte $07,$07,$07,$0a,$07,$08,$00,$00,$00,$0b,$0f,$0f,$0b,$08,$0b,$0b
.byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$07,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0c
.byte $0c,$0b,$0c,$0c,$0c,$0f,$0a,$0a,$0a,$07,$07,$0a,$07,$08,$08,$00
.byte $02,$0f,$02,$02,$08,$0b,$0b,$0a,$0a,$0b,$0b,$0b,$0b,$01,$07,$0c
.byte $0c,$0b,$0c,$0c,$06,$06,$0b,$0b,$0a,$0b,$0b,$0b,$0b,$0b,$0b,$00
.byte $0a,$07,$07,$07,$08,$08,$08,$08,$00,$08,$08,$07,$07,$0b,$00,$0f
.byte $0b,$00,$0f,$0b,$07,$0c,$0b,$0c,$0c,$06,$06,$06,$06,$06,$0b,$0b
.byte $0b,$0c,$0a,$00,$07,$0b,$00,$0b,$08,$08,$00,$08,$08,$00,$0b,$0b
.byte $0c,$0c,$07,$0f,$0b,$0f,$02,$02,$02,$02,$0c,$0c,$0c,$06,$06,$06
.byte $06,$06,$06,$06,$06,$06,$0b,$0b,$0b,$0b,$08,$0b,$00,$00,$00,$00
.byte $00,$00,$08,$00,$00,$00,$0b,$00,$0f,$0b,$07,$07,$02,$0b,$0c,$0c
.byte $0c,$0c,$06,$06,$06,$06,$0f,$0c,$06,$0b,$06,$0f,$0b,$0b,$0b,$00
.byte $00,$0f,$00,$00,$0b,$00,$00,$00,$00,$08,$08,$00,$07,$0b,$00,$00
.byte $0a,$07,$0a,$07,$0a,$0c,$0c,$0c,$06,$06,$06,$0f,$0f,$0f,$0f,$0f
.byte $0b,$0f,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0b,$0b,$00,$00
.byte $00,$00,$00,$07,$0c,$08,$00,$00,$00,$0f,$0f,$0f,$0f,$0c,$0c,$0c
.byte $0f,$0b,$0b,$0b,$00,$02,$0b,$0b,$0b,$0b,$0f,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$0b,$00,$00,$00,$00,$00,$00,$00,$0a,$00,$00
.byte $00,$00,$0f,$0f,$0b,$0b,$0b,$0f,$0b,$0b,$0b,$00,$0b,$0b,$0c,$0c
.byte $0c,$0b,$01,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0b,$00,$00
.byte $00,$00,$00,$00,$00,$00,$0a,$0a,$0a,$0a,$0a,$00,$0b,$00,$00,$00
.byte $00,$00,$0c,$0a,$0b,$0c,$00,$0b,$0b,$0b,$0b,$00,$00,$0b,$0b,$0a
.byte $0a,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$02,$0a,$08,$0a
.byte $0a,$0a,$0c,$0c,$0c,$0c,$0a,$0a,$0a,$0a,$0a,$0c,$0b,$00,$00,$00
.byte $00,$00,$00,$0a,$0a,$00,$00,$00,$0b,$0b,$00,$00,$00,$00,$00,$00
.byte $00,$00,$02,$00,$00,$00,$0a,$0a,$0a,$0a,$0a,$0b,$00,$0c,$08,$0a
.byte $0b,$00,$00,$0b,$0b,$0c,$0b,$0c,$0b,$0a,$0a,$00,$00,$00,$00,$00
.byte $0b,$0b,$0b,$00,$00,$00,$00,$00



; CharSet Attribute (L2) Data...
; 1000 attributes, 1 attribute per image, 8 bits per attribute, total size is 1000 ($3e8) bytes.
; nb. Upper nybbles = colour (screen matrix high), lower nybbles = colour (screen matrix low).

* = addr_charset_attrib_L2_data
charset_attrib_L2_data

.byte $78,$78,$78,$78,$78,$78,$78,$78,$7b,$8a,$8b,$ab,$0c,$ab,$17,$cb
.byte $c0,$80,$70,$78,$80,$80,$a8,$8b,$b8,$f0,$78,$78,$78,$78,$78,$78
.byte $78,$78,$78,$78,$78,$78,$78,$78,$7b,$70,$2b,$78,$7b,$ab,$8b,$ab
.byte $20,$20,$78,$70,$78,$87,$ba,$10,$17,$07,$07,$17,$17,$ab,$b7,$ba
.byte $b7,$b7,$7b,$7b,$7b,$7b,$7a,$7b,$78,$78,$78,$78,$7b,$78,$7b,$78
.byte $70,$c1,$b1,$a0,$1b,$80,$80,$78,$80,$2b,$7b,$7b,$17,$a7,$a7,$7a
.byte $a7,$0a,$87,$07,$0a,$78,$a8,$8b,$cb,$7b,$7b,$7b,$78,$7b,$8b,$7b
.byte $7b,$cb,$cb,$78,$78,$78,$78,$78,$ab,$b0,$a7,$b7,$78,$b7,$7b,$8b
.byte $8a,$7a,$a7,$a1,$1a,$87,$87,$7a,$8a,$80,$7a,$ab,$cb,$0b,$b2,$bc
.byte $c0,$20,$cb,$2c,$cb,$7b,$7b,$78,$78,$20,$0c,$c7,$78,$78,$78,$78
.byte $ab,$78,$80,$78,$b7,$a7,$a7,$87,$a1,$a7,$87,$a1,$8a,$87,$8a,$a7
.byte $7a,$0c,$ba,$0c,$a0,$0b,$0b,$bc,$0c,$c0,$0c,$0c,$0c,$08,$8c,$fc
.byte $cf,$7b,$17,$a7,$78,$78,$78,$78,$7b,$b0,$70,$07,$a1,$a7,$a7,$a1
.byte $78,$a1,$a1,$a7,$1a,$81,$17,$71,$a1,$80,$a0,$c0,$0b,$10,$0b,$01
.byte $c0,$0c,$20,$c0,$c0,$80,$08,$08,$a0,$0a,$0a,$a7,$77,$77,$77,$78
.byte $b0,$b7,$a8,$8a,$a8,$8a,$a8,$1a,$8a,$8a,$8a,$a8,$8a,$87,$8a,$07
.byte $fa,$20,$c0,$c0,$f0,$0c,$80,$21,$0b,$0c,$20,$0c,$0c,$c1,$8b,$2c
.byte $80,$a7,$ca,$a7,$71,$70,$71,$78,$78,$8a,$8a,$8a,$8a,$8a,$a8,$1a
.byte $8a,$1a,$87,$7a,$ca,$82,$28,$8a,$7a,$0b,$0a,$0b,$b0,$a8,$0c,$8c
.byte $0b,$cb,$0c,$cb,$0b,$0b,$8c,$ac,$b8,$a7,$1a,$a7,$71,$70,$71,$78
.byte $8b,$a7,$a7,$28,$28,$a8,$8a,$8a,$7a,$a2,$82,$7f,$a7,$70,$a7,$a2
.byte $80,$a8,$8b,$08,$ab,$c0,$8b,$0b,$bc,$08,$8c,$cb,$c1,$b0,$0b,$2c
.byte $cb,$87,$1a,$7b,$b1,$71,$70,$78,$08,$b8,$b8,$b8,$78,$a8,$07,$02
.byte $08,$20,$72,$b2,$b7,$a2,$f2,$80,$0a,$a2,$28,$2b,$b8,$ab,$28,$0f
.byte $0b,$10,$2b,$12,$2b,$01,$bc,$20,$7a,$87,$1a,$b2,$b1,$bc,$10,$cb
.byte $82,$78,$b0,$b8,$78,$a8,$a8,$28,$82,$28,$2b,$08,$8c,$0c,$70,$78
.byte $78,$2a,$0b,$8b,$8b,$20,$80,$80,$0c,$cf,$80,$20,$a8,$28,$cb,$c0
.byte $c8,$a8,$b0,$bf,$78,$7b,$7c,$f7,$2b,$b0,$7b,$02,$8a,$a7,$28,$28
.byte $8a,$b2,$b8,$28,$28,$a7,$b8,$07,$8a,$a8,$28,$0a,$ab,$08,$0b,$28
.byte $8f,$20,$cf,$0c,$c0,$7b,$20,$7b,$c2,$2b,$fb,$7b,$ab,$7c,$c7,$ab
.byte $ba,$ba,$82,$87,$a8,$87,$20,$80,$a0,$02,$78,$08,$a8,$8a,$2a,$0b
.byte $82,$28,$20,$c0,$b0,$a2,$28,$80,$f0,$cf,$c0,$c0,$c0,$c0,$c0,$fc
.byte $c0,$70,$78,$8a,$ca,$cb,$ab,$b7,$7a,$78,$8a,$87,$a8,$a7,$a0,$70
.byte $10,$27,$0b,$a8,$07,$2b,$2b,$8b,$8c,$08,$2c,$0c,$0c,$c0,$87,$ba
.byte $0b,$f1,$f0,$0b,$cb,$70,$c0,$0f,$f0,$fc,$fc,$bf,$fc,$ca,$7a,$0a
.byte $7a,$78,$8a,$87,$a8,$72,$28,$a8,$28,$02,$21,$20,$20,$b0,$02,$8c
.byte $fc,$2c,$6c,$76,$a6,$7c,$c7,$ba,$a2,$2c,$0c,$fc,$fc,$c0,$ac,$ba
.byte $bf,$c0,$0b,$0b,$0b,$cb,$8f,$b8,$77,$7a,$8a,$87,$8a,$20,$2a,$8b
.byte $b8,$a1,$10,$0b,$2a,$80,$a8,$0b,$c7,$ca,$ca,$ca,$c7,$b7,$a1,$fb
.byte $fb,$7c,$7b,$6b,$cb,$fb,$f0,$0c,$bc,$ac,$fc,$0c,$20,$2c,$20,$7b
.byte $78,$8a,$8a,$a8,$7a,$20,$0a,$0b,$28,$b2,$bc,$80,$0a,$c0,$7b,$ab
.byte $1f,$ba,$21,$7a,$ca,$b7,$fc,$b6,$f6,$bc,$bc,$7c,$7c,$7b,$cf,$8c
.byte $0c,$ba,$c8,$cb,$8b,$27,$ba,$70,$2a,$0a,$8a,$a7,$20,$82,$0a,$08
.byte $0f,$fb,$0b,$a7,$fc,$b1,$1b,$8b,$ba,$bc,$bf,$6b,$b6,$bc,$7c,$7c
.byte $7c,$bc,$78,$78,$cf,$fb,$fc,$c0,$ac,$80,$ab,$c0,$b8,$8a,$8b,$2b
.byte $82,$28,$2a,$a8,$b2,$ba,$28,$82,$cb,$fc,$bf,$fa,$a8,$2c,$fb,$fb
.byte $6b,$b6,$3c,$73,$cf,$cf,$c6,$6b,$bc,$6c,$1f,$16,$1f,$0f,$20,$2b
.byte $bf,$0b,$ba,$7b,$20,$7b,$2b,$8b,$82,$a0,$a0,$28,$a0,$8a,$82,$82
.byte $78,$1a,$78,$a8,$b8,$bf,$6b,$b6,$bc,$cb,$bf,$6b,$1b,$1b,$1b,$1b
.byte $af,$1b,$cb,$2b,$7b,$7b,$2b,$2b,$78,$2b,$78,$cb,$20,$20,$7b,$7b
.byte $78,$a7,$a7,$80,$a8,$b0,$b8,$28,$f8,$c1,$01,$21,$b0,$bf,$bf,$f1
.byte $6c,$fc,$20,$80,$8b,$a8,$2c,$2c,$ac,$0c,$1b,$8b,$7b,$2b,$2b,$2b
.byte $b2,$7b,$a7,$a7,$cb,$78,$7b,$78,$a8,$78,$82,$7a,$a8,$b8,$ba,$28
.byte $8a,$ba,$b0,$1b,$a0,$2c,$8a,$ab,$f7,$c0,$0c,$2b,$20,$fc,$bf,$bf
.byte $1f,$fc,$bf,$8b,$2b,$8b,$7b,$a8,$b7,$7a,$7a,$78,$72,$20,$7b,$78
.byte $82,$78,$28,$8a,$7b,$ab,$cb,$0b,$b0,$07,$b0,$ba,$0c,$8a,$a8,$82
.byte $7b,$bc,$ab,$cb,$ac,$7b,$cb,$0c,$0f,$f0,$20,$7b,$28,$02,$2a,$70
.byte $70,$a2,$7b,$72,$78,$7b,$7b,$78,$78,$78,$28,$82,$b0,$2b,$ba,$78
.byte $28,$c2,$ba,$ab,$ab,$fa,$0c,$0c,$fc,$fc,$fc,$ba,$0c,$cb,$2b,$2b
.byte $b8,$2a,$8a,$70,$b0,$ba,$8a,$78,$70,$70,$7b,$78,$78,$7b,$78,$78
.byte $78,$28,$08,$82,$a8,$ba,$8c,$c8,$c8,$c8,$b8,$8c,$cb,$08,$ca,$b8
.byte $a0,$cb,$82,$c0,$c0,$0b,$c0,$80,$a8,$82,$02,$2b,$8b,$78,$2b,$2b
.byte $02,$72,$70,$7b,$7b,$78,$7b,$7b



; Map Data...
; 40x25 (1000) cells, 8 bits per cell, total size is 1000 ($3e8) bytes.

* = addr_map_data
map_data

.byte $00,$01,$02,$03,$04,$05,$06,$07,$08,$09,$0a,$0b,$0c,$0d,$0e,$0f
.byte $10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$1a,$1b,$1c,$1d,$1e,$1f
.byte $20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$2a,$2b,$2c,$2d,$2e,$2f
.byte $30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$3a,$3b,$3c,$3d,$3e,$3f
.byte $40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c,$4d,$4e,$4f
.byte $50,$51,$52,$53,$54,$55,$56,$57,$58,$59,$5a,$5b,$5c,$5d,$5e,$5f
.byte $60,$61,$62,$63,$64,$65,$66,$67,$68,$69,$6a,$6b,$6c,$6d,$6e,$6f
.byte $70,$71,$72,$73,$74,$75,$76,$77,$78,$79,$7a,$7b,$7c,$7d,$7e,$7f
.byte $80,$81,$82,$83,$84,$85,$86,$87,$88,$89,$8a,$8b,$8c,$8d,$8e,$8f
.byte $90,$91,$92,$93,$94,$95,$96,$97,$98,$99,$9a,$9b,$9c,$9d,$9e,$9f
.byte $a0,$a1,$a2,$a3,$a4,$a5,$a6,$a7,$a8,$a9,$aa,$ab,$ac,$ad,$ae,$af
.byte $b0,$b1,$b2,$b3,$b4,$b5,$b6,$b7,$b8,$b9,$ba,$bb,$bc,$bd,$be,$bf
.byte $c0,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf
.byte $d0,$d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$da,$db,$dc,$dd,$de,$df
.byte $e0,$e1,$e2,$e3,$e4,$e5,$e6,$e7,$e8,$e9,$ea,$eb,$ec,$ed,$ee,$ef
.byte $f0,$f1,$f2,$f3,$f4,$f5,$f6,$f7,$f8,$f9,$fa,$fb,$fc,$fd,$fe,$ff
.byte $00,$01,$02,$03,$04,$05,$06,$07,$08,$09,$0a,$0b,$0c,$0d,$0e,$0f
.byte $10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$1a,$1b,$1c,$1d,$1e,$1f
.byte $20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$2a,$2b,$2c,$2d,$2e,$2f
.byte $30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$3a,$3b,$3c,$3d,$3e,$3f
.byte $40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c,$4d,$4e,$4f
.byte $50,$51,$52,$53,$54,$55,$56,$57,$58,$59,$5a,$5b,$5c,$5d,$5e,$5f
.byte $60,$61,$62,$63,$64,$65,$66,$67,$68,$69,$6a,$6b,$6c,$6d,$6e,$6f
.byte $70,$71,$72,$73,$74,$75,$76,$77,$78,$79,$7a,$7b,$7c,$7d,$7e,$7f
.byte $80,$81,$82,$83,$84,$85,$86,$87,$88,$89,$8a,$8b,$8c,$8d,$8e,$8f
.byte $90,$91,$92,$93,$94,$95,$96,$97,$98,$99,$9a,$9b,$9c,$9d,$9e,$9f
.byte $a0,$a1,$a2,$a3,$a4,$a5,$a6,$a7,$a8,$a9,$aa,$ab,$ac,$ad,$ae,$af
.byte $b0,$b1,$b2,$b3,$b4,$b5,$b6,$b7,$b8,$b9,$ba,$bb,$bc,$bd,$be,$bf
.byte $c0,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf
.byte $d0,$d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$da,$db,$dc,$dd,$de,$df
.byte $e0,$e1,$e2,$e3,$e4,$e5,$e6,$e7,$e8,$e9,$ea,$eb,$ec,$ed,$ee,$ef
.byte $f0,$f1,$f2,$f3,$f4,$f5,$f6,$f7,$f8,$f9,$fa,$fb,$fc,$fd,$fe,$ff
.byte $00,$01,$02,$03,$04,$05,$06,$07,$08,$09,$0a,$0b,$0c,$0d,$0e,$0f
.byte $10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$1a,$1b,$1c,$1d,$1e,$1f
.byte $20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$2a,$2b,$2c,$2d,$2e,$2f
.byte $30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$3a,$3b,$3c,$3d,$3e,$3f
.byte $40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c,$4d,$4e,$4f
.byte $50,$51,$52,$53,$54,$55,$56,$57,$58,$59,$5a,$5b,$5c,$5d,$5e,$5f
.byte $60,$61,$62,$63,$64,$65,$66,$67,$68,$69,$6a,$6b,$6c,$6d,$6e,$6f
.byte $70,$71,$72,$73,$74,$75,$76,$77,$78,$79,$7a,$7b,$7c,$7d,$7e,$7f
.byte $80,$81,$82,$83,$84,$85,$86,$87,$88,$89,$8a,$8b,$8c,$8d,$8e,$8f
.byte $90,$91,$92,$93,$94,$95,$96,$97,$98,$99,$9a,$9b,$9c,$9d,$9e,$9f
.byte $a0,$a1,$a2,$a3,$a4,$a5,$a6,$a7,$a8,$a9,$aa,$ab,$ac,$ad,$ae,$af
.byte $b0,$b1,$b2,$b3,$b4,$b5,$b6,$b7,$b8,$b9,$ba,$bb,$bc,$bd,$be,$bf
.byte $c0,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf
.byte $d0,$d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$da,$db,$dc,$dd,$de,$df
.byte $e0,$e1,$e2,$e3,$e4,$e5,$e6,$e7,$e8,$e9,$ea,$eb,$ec,$ed,$ee,$ef
.byte $f0,$f1,$f2,$f3,$f4,$f5,$f6,$f7,$f8,$f9,$fa,$fb,$fc,$fd,$fe,$ff
.byte $00,$01,$02,$03,$04,$05,$06,$07,$08,$09,$0a,$0b,$0c,$0d,$0e,$0f
.byte $10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$1a,$1b,$1c,$1d,$1e,$1f
.byte $20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$2a,$2b,$2c,$2d,$2e,$2f
.byte $30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$3a,$3b,$3c,$3d,$3e,$3f
.byte $40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c,$4d,$4e,$4f
.byte $50,$51,$52,$53,$54,$55,$56,$57,$58,$59,$5a,$5b,$5c,$5d,$5e,$5f
.byte $60,$61,$62,$63,$64,$65,$66,$67,$68,$69,$6a,$6b,$6c,$6d,$6e,$6f
.byte $70,$71,$72,$73,$74,$75,$76,$77,$78,$79,$7a,$7b,$7c,$7d,$7e,$7f
.byte $80,$81,$82,$83,$84,$85,$86,$87,$88,$89,$8a,$8b,$8c,$8d,$8e,$8f
.byte $90,$91,$92,$93,$94,$95,$96,$97,$98,$99,$9a,$9b,$9c,$9d,$9e,$9f
.byte $a0,$a1,$a2,$a3,$a4,$a5,$a6,$a7,$a8,$a9,$aa,$ab,$ac,$ad,$ae,$af
.byte $b0,$b1,$b2,$b3,$b4,$b5,$b6,$b7,$b8,$b9,$ba,$bb,$bc,$bd,$be,$bf
.byte $c0,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf
.byte $d0,$d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$da,$db,$dc,$dd,$de,$df
.byte $e0,$e1,$e2,$e3,$e4,$e5,$e6,$e7


